name: CI

on:
  workflow_dispatch:

jobs:
  do-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/set-up-ci
        with:
          node-version: 22
     
