name: CI

on:
  workflow_dispatch:

jobs:
  do-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/set-up-ci
        with:
          node-version: 22
      - name: Use correct npm version via Corepack
        run: |
         corepack enable
         corepack prepare npm@11.5.1 --activate
